### ISSUE TITLE
How to turn off VoiceOver?

### ISSUE THREAD

**Issue by Mortennn** [drselump14/alfred-change-sound-output#2]
Every time I switch output device VoiceOver tells me which output device I selected. How can I turn this off?

Thanks for this awesome workflow! Really useful👍

**Comment by drselump14** [comment]
what you have to do is to remove this line

https://github.com/drselump14/alfred-change-sound-output/blob/8c387af40d7457ab083e5de14e6b20021c772a16/info.plist#L94

I hope it helps

**Comment by Mortennn** [comment]
It does. Thank you👍
